[package]
name = "todo_backend"
version = "0.1.0"
authors = ["Duda Dornelles <dudassdornelles@gmail.com>"]

[dependencies]
iron = "*"
router = "*"
uuid = "*"
rustc-serialize = "*"

[dependencies.bodyparser]
git = "https://github.com/iron/body-parser.git"
